export const PLAY_SOUND = "PLAY_SOUND";
export const PAUSE_SOUND = "PAUSE_SOUND";
export const SET_ACTIVE_SOUND = "SET_ACTIVE_SOUND";
export const SET_PLAYLIST = "SET_PLAYLIST";

export const GET_TOP_PLAYLISTS_SUCCESS = "GET_TOP_PLAYLISTS_SUCCESS";
export const GET_TOP_PLAYLISTS_PENDING = "GET_TOP_PLAYLISTS_PENDING";

export const GET_TOP_ALBUMS_SUCCESS = "GET_TOP_ALBUMS_SUCCESS";
export const GET_TOP_ALBUMS_PENDING = "GET_TOP_ALBUMS_PENDING";

export const GET_TOP_TRACKS = "GET_TOP_TRACKS";
export const GET_TOP_TRACKS_SUCCESS = "GET_TOP_TRACKS_SUCCESS";
